### ISSUE TITLE
請加入支持移動版的kiwi browser 

### ISSUE THREAD

**Issue by Benlee1129** [muzuiget/monkey-support#1]
使用kiwi-browser 時，因相容檢測問題而無法直接在 chrome extension store 中下載wildmonkey，我手動至Microsoft edge store 下載來安裝，請加入kiwi-browser 相容使可直接在chrome extension store中下載。
為了能在Dualsub 中改變字型，繞了一大圈。

**Comment by muzuiget** [comment]
这已经正常了吧？

**Comment by Benlee1129** [comment]
可以100%功能在kiwi browser中使用Dualsub。
但在Chrome 商店中搜尋不到Dualsub，需要至Microsoft edge 商店內下載。

muzuiget ***@***.***> 於 2023年5月27日 週六 08:17 寫道：

**Comment by muzuiget** [comment]
Kiwi 的自己问题。
