### ISSUE TITLE
ios orion浏览器不能正常显示脚本

### ISSUE THREAD

**Issue by xiaoyuhaoge** [muzuiget/monkey-support#2]
在iOS的orion浏览器不会正常显示当前页面可用的脚本
![IMG_6823](https://github.com/muzuiget/monkey-support/assets/134502767/647c0d36-0ebe-454a-8c88-fcc8f3ddc76e)

**Comment by muzuiget** [comment]
这个浏览器我测试过了，它的 API 兼容性不好，不兼容 [Content scripts 的 Message 接口](https://developer.chrome.com/docs/extensions/mv3/content_scripts/)。

我是写了个 Hello 那种最简单的扩展代码去测试的，甚至只用 Manifest V2 定义的接口，测出那个不兼容的 API。

它的支持论坛 https://orionfeedback.org/t/extensions 一大堆不兼容扩展报告，我倒想知道哪些扩展能正常运行，好让我参考参考。

**Comment by muzuiget** [comment]
v0.14.0 已经可以在 Orion 里运行，类似兼容性问题见 https://github.com/muzuiget/dualsub-support/issues/552
