### ISSUE TITLE
没有权限

### ISSUE THREAD

**Issue by ktwotanke** [muzuiget/monkey-support#3]
已经开放了权限，插件提示扩展没有访问当前页面的权限。

**Comment by muzuiget** [comment]
请问在哪个浏览器？

要等网页加载完毕，在 `document_idle` 状态时，扩展脚本才会被浏览器运行。

**Comment by ktwotanke** [comment]
> 请问在哪个浏览器？
> 
> 要等网页加载完毕，在 `document_idle` 状态时，扩展脚本才会被浏览器运行。

ok了，谢谢
