### ISSUE TITLE
Firefox 版本 v0.6.6 似乎無法搭配 Dualsub v2.28.0 改變字幕樣式

### ISSUE THREAD

**Issue by gnafrgb** [muzuiget/monkey-support#4]
本來可以同時用這兩個套件在Netflix顯示雙字幕並且改顏色字體大小之類的
但突然就不行了

播放時顯示有匹配到Netflix網址
但沒有改變字幕樣式
只有dualsub原本內建的基本字幕樣式還有作用
![shot](https://github.com/muzuiget/monkey-support/assets/72696475/1a166530-84b6-414b-9f13-739acc8ac583)

**Comment by muzuiget** [comment]
因为在 Dualsub 2.27.0 里我重写的标准模式的通用渲染器，HTML 结构和之前的版本不同了。

你可以贴一下原来的 CSS 是怎么写的，然后我替你改一下。

**Comment by gnafrgb** [comment]
原本的是這樣

.dualsub-renderer .subtitles .contents {
    color: rgb(255, 255, 0);
    font-size: 42px;
    background-color: rgba(0, 0, 0, 0.4);
    padding: 3px;
}

.dualsub-renderer .subtitle-2 .contents {
    color: rgb(255,255,255);
    font-size: 18px;
    background-color: transparent;
    text-shadow: 2px 2px 1px rgba(0,0,0,1);
}

**Comment by gnafrgb** [comment]
去掉之後有變更字幕的顏色跟大小
但是次字幕也跟主字幕一樣有半透明黑背景了

![Firefox_Screenshot_2024-04-11T17-04-09 383Z](https://github.com/muzuiget/monkey-support/assets/72696475/331f7154-94dc-40ba-b091-94e7fc8e5d80)

**Comment by muzuiget** [comment]
半透明背景是扩展添加的，你试下在扩展的**基础样式**改成**原状**。

然后再使用以下代码。

```
.dualsub-renderer .subtitle-1 {
    color: rgb(255, 255, 0);
    font-size: 42px;
    background-color: rgba(0, 0, 0, 0.4);
    padding: 3px;
}

.dualsub-renderer .subtitle-2 {
    color: rgb(255,255,255);
    font-size: 18px;
    background-color: transparent;
    text-shadow: 2px 2px 1px rgba(0,0,0,1);
}
```

**Comment by gnafrgb** [comment]
感謝! 
測試後已正常

**Comment by muzuiget** [comment]
最近我提交了 Wildmonkey 0.16.2 到 Firefox，等待审核通过。升级到 Manifest V3 版本，跟 Chrome 版本使用相同代码。

但是 Firefox 现在对 Manifest V3 权限处理是**按需授权**，用户需要单独对每个网站独立授权，所以从 Manifest V2 升级到 Manifest V3 后，扩展会突然失效。

通过对工具栏图标右键设置授权，类似这样：

![Screenshot_20240412_183558](https://github.com/muzuiget/monkey-support/assets/330812/92e75d0a-62a5-4ac0-a111-001112e4073c)
