### ISSUE TITLE
I don't understand URL setup

### ISSUE THREAD

**Issue by hirntot** [muzuiget/monkey-support#5]
hi! thanks for this lightweight script monkey, that's exactly what I'm looking for since greasemonkey is too heavy for my small purpose.
my script is running nicely when activated - but it doesn't activate automatically.

in the readme you wrote:
"URL patterns to execute the code automatically."
so I added '*', when that wasn't working, I asked chatGPT and added '*://*/*' and 'https://*/*', but after reloading the page, it never started automatically. What am I doing wrong?

**Comment by muzuiget** [comment]
Hi

The *Urls* pattern is one pattern per line.

![Screenshot_20240703_164212](https://github.com/muzuiget/monkey-support/assets/330812/d28e7596-2fc4-47bf-b469-925d31b2aa17)

* Execute automatically on any url which starts with `https://www.example.com/`.
* Execute automatically on `https://www.httpbin.org/headers`.

**Comment by hirntot** [comment]
I'm sorry, there was a formatting problem with my initial post, due to markdown support.
I would like to start the script automatically on _every_ site. what do I insert in the URL section? I tested following lines.
```
*
*://*/*
https://*/*
http://*/*
``` 
without success.

also, you wrote `<all_urls>.` **won't** be supported, but what **would** be supported?

**Comment by muzuiget** [comment]
The current Match Pattern implementation does not support this syntax.

If you are a skilled script writer, you can actually write it as a standalone extension directly, which only requires two files, a `manifest.json` and your script.

**Comment by muzuiget** [comment]
As I said above, if you need these features, just write a browser extension.

You only need two files:

* manifest.json
* sytles.css

```
{
    "manifest_version": 3,
    "name": "hello",
    "version": "0.1.0",
    "content_scripts": [
        {
            "matches": [
                "<all_urls>"
            ],
            "css": [
                "styles.css"
            ]
        }
    ]
}
```

https://developer.chrome.com/docs/extensions/reference/manifest/content-scripts
